version: "3.9"
services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
