version: "3"
services:
  app:
    container_name: app
    restart: always
    # image: tag from docker Hub
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 4000:4000
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mynet
    depends_on: 
      db:
        condition: service_started
  db:
    container_name: db
    build:
      dockerfile: src/db/Dockerfile
      context: .
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - mynet 

networks:
  mynet:
    driver: bridge

volumes:
  db-data: